services:
  - type: web
    name: shoppingbill
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python scripts/init_prod.py && gunicorn shop_system.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: shop_system.settings
      - key: DEBUG
        value: "False"
