# Generated by Django 5.2.3 on 2026-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_product_image_alter_bill_id_alter_billitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
